services:
  app:
    build: .
    container_name: dara_framework
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: mariadb:latest
    container_name: dara_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: dba
      MYSQL_PASSWORD: qwe123
    ports:
      - "3308:3306"